/**
 * Gecad ePayment API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CardPaymentOption;
import io.swagger.client.model.InstallmentsPaymentOption;
import io.swagger.client.model.LoyaltyPointsPaymentOption;
import io.swagger.client.model.TokenizedCardPaymentOption;


/**
 * References all payment options available through ALU protocol
 */
@ApiModel(description = "References all payment options available through ALU protocol")

public class AluPaymentOption   {
  @SerializedName("creditCard")
  private CardPaymentOption creditCard = null;

  @SerializedName("token")
  private TokenizedCardPaymentOption token = null;

  @SerializedName("installments")
  private InstallmentsPaymentOption installments = null;

  @SerializedName("loyaltyPoints")
  private LoyaltyPointsPaymentOption loyaltyPoints = null;

  public AluPaymentOption creditCard(CardPaymentOption creditCard) {
    this.creditCard = creditCard;
    return this;
  }

   /**
   * Get creditCard
   * @return creditCard
  **/
  @ApiModelProperty(example = "null", value = "")
  public CardPaymentOption getCreditCard() {
    return creditCard;
  }

  public void setCreditCard(CardPaymentOption creditCard) {
    this.creditCard = creditCard;
  }

  public AluPaymentOption token(TokenizedCardPaymentOption token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(example = "null", value = "")
  public TokenizedCardPaymentOption getToken() {
    return token;
  }

  public void setToken(TokenizedCardPaymentOption token) {
    this.token = token;
  }

  public AluPaymentOption installments(InstallmentsPaymentOption installments) {
    this.installments = installments;
    return this;
  }

   /**
   * Get installments
   * @return installments
  **/
  @ApiModelProperty(example = "null", value = "")
  public InstallmentsPaymentOption getInstallments() {
    return installments;
  }

  public void setInstallments(InstallmentsPaymentOption installments) {
    this.installments = installments;
  }

  public AluPaymentOption loyaltyPoints(LoyaltyPointsPaymentOption loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
    return this;
  }

   /**
   * Get loyaltyPoints
   * @return loyaltyPoints
  **/
  @ApiModelProperty(example = "null", value = "")
  public LoyaltyPointsPaymentOption getLoyaltyPoints() {
    return loyaltyPoints;
  }

  public void setLoyaltyPoints(LoyaltyPointsPaymentOption loyaltyPoints) {
    this.loyaltyPoints = loyaltyPoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AluPaymentOption aluPaymentOption = (AluPaymentOption) o;
    return Objects.equals(this.creditCard, aluPaymentOption.creditCard) &&
        Objects.equals(this.token, aluPaymentOption.token) &&
        Objects.equals(this.installments, aluPaymentOption.installments) &&
        Objects.equals(this.loyaltyPoints, aluPaymentOption.loyaltyPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCard, token, installments, loyaltyPoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AluPaymentOption {\n");
    
    sb.append("    creditCard: ").append(toIndentedString(creditCard)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    installments: ").append(toIndentedString(installments)).append("\n");
    sb.append("    loyaltyPoints: ").append(toIndentedString(loyaltyPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

