/**
 * Gecad ePayment API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Pay with credit card
 */
@ApiModel(description = "Pay with credit card")

public class CardPaymentOption   {
  @SerializedName("ccNumber")
  private String ccNumber = null;

  @SerializedName("ccOwner")
  private String ccOwner = null;

  @SerializedName("expMonth")
  private Integer expMonth = null;

  @SerializedName("expYear")
  private Integer expYear = null;

  @SerializedName("cvv")
  private Integer cvv = null;

  @SerializedName("enableToken")
  private Boolean enableToken = null;

  @SerializedName("ccNumberTime")
  private String ccNumberTime = null;

  @SerializedName("ccOwnerTime")
  private String ccOwnerTime = null;

  public CardPaymentOption ccNumber(String ccNumber) {
    this.ccNumber = ccNumber;
    return this;
  }

   /**
   * The card number on which the order authorization will be made 
   * @return ccNumber
  **/
  @ApiModelProperty(example = "null", value = "The card number on which the order authorization will be made ")
  public String getCcNumber() {
    return ccNumber;
  }

  public void setCcNumber(String ccNumber) {
    this.ccNumber = ccNumber;
  }

  public CardPaymentOption ccOwner(String ccOwner) {
    this.ccOwner = ccOwner;
    return this;
  }

   /**
   * The card owner name, as it appears on the card. 
   * @return ccOwner
  **/
  @ApiModelProperty(example = "null", value = "The card owner name, as it appears on the card. ")
  public String getCcOwner() {
    return ccOwner;
  }

  public void setCcOwner(String ccOwner) {
    this.ccOwner = ccOwner;
  }

  public CardPaymentOption expMonth(Integer expMonth) {
    this.expMonth = expMonth;
    return this;
  }

   /**
   * The month in which the card used expires 
   * @return expMonth
  **/
  @ApiModelProperty(example = "null", value = "The month in which the card used expires ")
  public Integer getExpMonth() {
    return expMonth;
  }

  public void setExpMonth(Integer expMonth) {
    this.expMonth = expMonth;
  }

  public CardPaymentOption expYear(Integer expYear) {
    this.expYear = expYear;
    return this;
  }

   /**
   * The year in which the card used expires 
   * @return expYear
  **/
  @ApiModelProperty(example = "null", value = "The year in which the card used expires ")
  public Integer getExpYear() {
    return expYear;
  }

  public void setExpYear(Integer expYear) {
    this.expYear = expYear;
  }

  public CardPaymentOption cvv(Integer cvv) {
    this.cvv = cvv;
    return this;
  }

   /**
   * The CCV/CVV2 code for the card. For some card types or  based on merchant settings this can be empty,  otherwise it should have a numerical value 
   * @return cvv
  **/
  @ApiModelProperty(example = "null", value = "The CCV/CVV2 code for the card. For some card types or  based on merchant settings this can be empty,  otherwise it should have a numerical value ")
  public Integer getCvv() {
    return cvv;
  }

  public void setCvv(Integer cvv) {
    this.cvv = cvv;
  }

  public CardPaymentOption enableToken(Boolean enableToken) {
    this.enableToken = enableToken;
    return this;
  }

   /**
   * Enable Token payments for the order. For the initial transaction,  we have this parameter set to 1 
   * @return enableToken
  **/
  @ApiModelProperty(example = "null", value = "Enable Token payments for the order. For the initial transaction,  we have this parameter set to 1 ")
  public Boolean getEnableToken() {
    return enableToken;
  }

  public void setEnableToken(Boolean enableToken) {
    this.enableToken = enableToken;
  }

  public CardPaymentOption ccNumberTime(String ccNumberTime) {
    this.ccNumberTime = ccNumberTime;
    return this;
  }

   /**
   * Time spent by user to insert card number 
   * @return ccNumberTime
  **/
  @ApiModelProperty(example = "null", value = "Time spent by user to insert card number ")
  public String getCcNumberTime() {
    return ccNumberTime;
  }

  public void setCcNumberTime(String ccNumberTime) {
    this.ccNumberTime = ccNumberTime;
  }

  public CardPaymentOption ccOwnerTime(String ccOwnerTime) {
    this.ccOwnerTime = ccOwnerTime;
    return this;
  }

   /**
   * Time spent by user to insert card owner 
   * @return ccOwnerTime
  **/
  @ApiModelProperty(example = "null", value = "Time spent by user to insert card owner ")
  public String getCcOwnerTime() {
    return ccOwnerTime;
  }

  public void setCcOwnerTime(String ccOwnerTime) {
    this.ccOwnerTime = ccOwnerTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardPaymentOption cardPaymentOption = (CardPaymentOption) o;
    return Objects.equals(this.ccNumber, cardPaymentOption.ccNumber) &&
        Objects.equals(this.ccOwner, cardPaymentOption.ccOwner) &&
        Objects.equals(this.expMonth, cardPaymentOption.expMonth) &&
        Objects.equals(this.expYear, cardPaymentOption.expYear) &&
        Objects.equals(this.cvv, cardPaymentOption.cvv) &&
        Objects.equals(this.enableToken, cardPaymentOption.enableToken) &&
        Objects.equals(this.ccNumberTime, cardPaymentOption.ccNumberTime) &&
        Objects.equals(this.ccOwnerTime, cardPaymentOption.ccOwnerTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ccNumber, ccOwner, expMonth, expYear, cvv, enableToken, ccNumberTime, ccOwnerTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardPaymentOption {\n");
    
    sb.append("    ccNumber: ").append(toIndentedString(ccNumber)).append("\n");
    sb.append("    ccOwner: ").append(toIndentedString(ccOwner)).append("\n");
    sb.append("    expMonth: ").append(toIndentedString(expMonth)).append("\n");
    sb.append("    expYear: ").append(toIndentedString(expYear)).append("\n");
    sb.append("    cvv: ").append(toIndentedString(cvv)).append("\n");
    sb.append("    enableToken: ").append(toIndentedString(enableToken)).append("\n");
    sb.append("    ccNumberTime: ").append(toIndentedString(ccNumberTime)).append("\n");
    sb.append("    ccOwnerTime: ").append(toIndentedString(ccOwnerTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

