/*
 * Gecad ePayment API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * An item belonging to ALU request
 */
@ApiModel(description = "An item belonging to ALU request")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T17:53:39.583+02:00")
public class OrderItem {
  @SerializedName("name")
  private String name = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("info")
  private String info = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("vat")
  private BigDecimal vat = null;

  /**
   * Specify if ORDER_PRICE[0] parameter includes VAT or not. * GROSS (VAT is included) * NET (VAT will be added by PayU) 
   */
  public enum PriceTypeEnum {
    @SerializedName("GROSS")
    GROSS("GROSS"),
    
    @SerializedName("NET")
    NET("NET");

    private String value;

    PriceTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("priceType")
  private PriceTypeEnum priceType = PriceTypeEnum.NET;

  @SerializedName("quantity")
  private Integer quantity = null;

  public OrderItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Order item name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Order item name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrderItem code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Product code. If multiple products are sent (in the same or subsequent transactions) with the same product code, PayU will update the product with  the corresponding index (overwriting all the other product information - name, price, taxes). 
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "Product code. If multiple products are sent (in the same or subsequent transactions) with the same product code, PayU will update the product with  the corresponding index (overwriting all the other product information - name, price, taxes). ")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OrderItem info(String info) {
    this.info = info;
    return this;
  }

   /**
   * Holds additional information about this order item 
   * @return info
  **/
  @ApiModelProperty(example = "null", value = "Holds additional information about this order item ")
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }

  public OrderItem version(String version) {
    this.version = version;
    return this;
  }

   /**
   * First item in the so-called array of product version for all ordered products 
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "First item in the so-called array of product version for all ordered products ")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public OrderItem price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Unit price for product. Default currency is set by PRICES_CURRENCY 
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "Unit price for product. Default currency is set by PRICES_CURRENCY ")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public OrderItem vat(BigDecimal vat) {
    this.vat = vat;
    return this;
  }

   /**
   * VAT value for product
   * minimum: 0.0
   * maximum: 1.0
   * @return vat
  **/
  @ApiModelProperty(example = "null", value = "VAT value for product")
  public BigDecimal getVat() {
    return vat;
  }

  public void setVat(BigDecimal vat) {
    this.vat = vat;
  }

  public OrderItem priceType(PriceTypeEnum priceType) {
    this.priceType = priceType;
    return this;
  }

   /**
   * Specify if ORDER_PRICE[0] parameter includes VAT or not. * GROSS (VAT is included) * NET (VAT will be added by PayU) 
   * @return priceType
  **/
  @ApiModelProperty(example = "null", value = "Specify if ORDER_PRICE[0] parameter includes VAT or not. * GROSS (VAT is included) * NET (VAT will be added by PayU) ")
  public PriceTypeEnum getPriceType() {
    return priceType;
  }

  public void setPriceType(PriceTypeEnum priceType) {
    this.priceType = priceType;
  }

  public OrderItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Number of items
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "Number of items")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItem orderItem = (OrderItem) o;
    return Objects.equals(this.name, orderItem.name) &&
        Objects.equals(this.code, orderItem.code) &&
        Objects.equals(this.info, orderItem.info) &&
        Objects.equals(this.version, orderItem.version) &&
        Objects.equals(this.price, orderItem.price) &&
        Objects.equals(this.vat, orderItem.vat) &&
        Objects.equals(this.priceType, orderItem.priceType) &&
        Objects.equals(this.quantity, orderItem.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, code, info, version, price, vat, priceType, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    priceType: ").append(toIndentedString(priceType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

