/*
 * Gecad ePayment API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WireAccountRaw
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T17:53:39.583+02:00")
public class WireAccountRaw {
  @SerializedName("BANK_IDENTIFIER")
  private String BANK_IDENTIFIER = null;

  @SerializedName("BANK_ACCOUNT")
  private String BANK_ACCOUNT = null;

  @SerializedName("ROUTING_NUMBER")
  private String ROUTING_NUMBER = null;

  @SerializedName("IBAN_ACCOUNT")
  private String IBAN_ACCOUNT = null;

  @SerializedName("BANK_SWIFT")
  private String BANK_SWIFT = null;

  @SerializedName("COUNTRY")
  private String COUNTRY = null;

  @SerializedName("WIRE_RECIPIENT_NAME")
  private String WIRE_RECIPIENT_NAME = null;

  @SerializedName("WIRE_RECIPIENT_VAT_ID")
  private String WIRE_RECIPIENT_VAT_ID = null;

  public WireAccountRaw BANK_IDENTIFIER(String BANK_IDENTIFIER) {
    this.BANK_IDENTIFIER = BANK_IDENTIFIER;
    return this;
  }

   /**
   * Bank identifier
   * @return BANK_IDENTIFIER
  **/
  @ApiModelProperty(example = "null", value = "Bank identifier")
  public String getBANKIDENTIFIER() {
    return BANK_IDENTIFIER;
  }

  public void setBANKIDENTIFIER(String BANK_IDENTIFIER) {
    this.BANK_IDENTIFIER = BANK_IDENTIFIER;
  }

  public WireAccountRaw BANK_ACCOUNT(String BANK_ACCOUNT) {
    this.BANK_ACCOUNT = BANK_ACCOUNT;
    return this;
  }

   /**
   * Bank account
   * @return BANK_ACCOUNT
  **/
  @ApiModelProperty(example = "null", value = "Bank account")
  public String getBANKACCOUNT() {
    return BANK_ACCOUNT;
  }

  public void setBANKACCOUNT(String BANK_ACCOUNT) {
    this.BANK_ACCOUNT = BANK_ACCOUNT;
  }

  public WireAccountRaw ROUTING_NUMBER(String ROUTING_NUMBER) {
    this.ROUTING_NUMBER = ROUTING_NUMBER;
    return this;
  }

   /**
   * Bank routing number
   * @return ROUTING_NUMBER
  **/
  @ApiModelProperty(example = "null", value = "Bank routing number")
  public String getROUTINGNUMBER() {
    return ROUTING_NUMBER;
  }

  public void setROUTINGNUMBER(String ROUTING_NUMBER) {
    this.ROUTING_NUMBER = ROUTING_NUMBER;
  }

  public WireAccountRaw IBAN_ACCOUNT(String IBAN_ACCOUNT) {
    this.IBAN_ACCOUNT = IBAN_ACCOUNT;
    return this;
  }

   /**
   * IBAN account
   * @return IBAN_ACCOUNT
  **/
  @ApiModelProperty(example = "null", value = "IBAN account")
  public String getIBANACCOUNT() {
    return IBAN_ACCOUNT;
  }

  public void setIBANACCOUNT(String IBAN_ACCOUNT) {
    this.IBAN_ACCOUNT = IBAN_ACCOUNT;
  }

  public WireAccountRaw BANK_SWIFT(String BANK_SWIFT) {
    this.BANK_SWIFT = BANK_SWIFT;
    return this;
  }

   /**
   * Bank swift
   * @return BANK_SWIFT
  **/
  @ApiModelProperty(example = "null", value = "Bank swift")
  public String getBANKSWIFT() {
    return BANK_SWIFT;
  }

  public void setBANKSWIFT(String BANK_SWIFT) {
    this.BANK_SWIFT = BANK_SWIFT;
  }

  public WireAccountRaw COUNTRY(String COUNTRY) {
    this.COUNTRY = COUNTRY;
    return this;
  }

   /**
   * Country
   * @return COUNTRY
  **/
  @ApiModelProperty(example = "null", value = "Country")
  public String getCOUNTRY() {
    return COUNTRY;
  }

  public void setCOUNTRY(String COUNTRY) {
    this.COUNTRY = COUNTRY;
  }

  public WireAccountRaw WIRE_RECIPIENT_NAME(String WIRE_RECIPIENT_NAME) {
    this.WIRE_RECIPIENT_NAME = WIRE_RECIPIENT_NAME;
    return this;
  }

   /**
   * Wire payment Recipient name
   * @return WIRE_RECIPIENT_NAME
  **/
  @ApiModelProperty(example = "null", value = "Wire payment Recipient name")
  public String getWIRERECIPIENTNAME() {
    return WIRE_RECIPIENT_NAME;
  }

  public void setWIRERECIPIENTNAME(String WIRE_RECIPIENT_NAME) {
    this.WIRE_RECIPIENT_NAME = WIRE_RECIPIENT_NAME;
  }

  public WireAccountRaw WIRE_RECIPIENT_VAT_ID(String WIRE_RECIPIENT_VAT_ID) {
    this.WIRE_RECIPIENT_VAT_ID = WIRE_RECIPIENT_VAT_ID;
    return this;
  }

   /**
   * Wire payment recipient VAT id
   * @return WIRE_RECIPIENT_VAT_ID
  **/
  @ApiModelProperty(example = "null", value = "Wire payment recipient VAT id")
  public String getWIRERECIPIENTVATID() {
    return WIRE_RECIPIENT_VAT_ID;
  }

  public void setWIRERECIPIENTVATID(String WIRE_RECIPIENT_VAT_ID) {
    this.WIRE_RECIPIENT_VAT_ID = WIRE_RECIPIENT_VAT_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WireAccountRaw wireAccountRaw = (WireAccountRaw) o;
    return Objects.equals(this.BANK_IDENTIFIER, wireAccountRaw.BANK_IDENTIFIER) &&
        Objects.equals(this.BANK_ACCOUNT, wireAccountRaw.BANK_ACCOUNT) &&
        Objects.equals(this.ROUTING_NUMBER, wireAccountRaw.ROUTING_NUMBER) &&
        Objects.equals(this.IBAN_ACCOUNT, wireAccountRaw.IBAN_ACCOUNT) &&
        Objects.equals(this.BANK_SWIFT, wireAccountRaw.BANK_SWIFT) &&
        Objects.equals(this.COUNTRY, wireAccountRaw.COUNTRY) &&
        Objects.equals(this.WIRE_RECIPIENT_NAME, wireAccountRaw.WIRE_RECIPIENT_NAME) &&
        Objects.equals(this.WIRE_RECIPIENT_VAT_ID, wireAccountRaw.WIRE_RECIPIENT_VAT_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(BANK_IDENTIFIER, BANK_ACCOUNT, ROUTING_NUMBER, IBAN_ACCOUNT, BANK_SWIFT, COUNTRY, WIRE_RECIPIENT_NAME, WIRE_RECIPIENT_VAT_ID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WireAccountRaw {\n");
    
    sb.append("    BANK_IDENTIFIER: ").append(toIndentedString(BANK_IDENTIFIER)).append("\n");
    sb.append("    BANK_ACCOUNT: ").append(toIndentedString(BANK_ACCOUNT)).append("\n");
    sb.append("    ROUTING_NUMBER: ").append(toIndentedString(ROUTING_NUMBER)).append("\n");
    sb.append("    IBAN_ACCOUNT: ").append(toIndentedString(IBAN_ACCOUNT)).append("\n");
    sb.append("    BANK_SWIFT: ").append(toIndentedString(BANK_SWIFT)).append("\n");
    sb.append("    COUNTRY: ").append(toIndentedString(COUNTRY)).append("\n");
    sb.append("    WIRE_RECIPIENT_NAME: ").append(toIndentedString(WIRE_RECIPIENT_NAME)).append("\n");
    sb.append("    WIRE_RECIPIENT_VAT_ID: ").append(toIndentedString(WIRE_RECIPIENT_VAT_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

